version: 2

jobs:
  build:
    docker:
      - image: docker:latest

    working_directory: /app

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build docker image
          command: |
            TAG=eu.gcr.io/zdev-com/zdev-website:build-$CIRCLE_BUILD_NUM
            docker build -t $TAG .

      - run:
          name: Push docker image when on master
          command: |
            TAG=eu.gcr.io/zdev-com/zdev-website:build-$CIRCLE_BUILD_NUM
            
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo $GCR_CREDENTIALS | docker login -u _json_key --password-stdin https://eu.gcr.io
              docker tag $TAG eu.gcr.io/zdev-com/zdev-website:latest
              docker push eu.gcr.io/zdev-com/zdev-website:latest
            fi